// Generated by scripts/bundle-api-talk.mjs — do not edit

// src/packs/sliders.ts
var SEMANTIC_SLIDERS = [
  {
    id: "exposure",
    label: "Exposure",
    effectId: "exposure",
    paramKey: "amount",
    min: -2,
    max: 2,
    step: 0.01
  },
  {
    id: "contrast",
    label: "Contrast",
    effectId: "contrast",
    paramKey: "amount",
    min: -1,
    max: 1,
    step: 0.01
  },
  {
    id: "warmth",
    label: "Warmth",
    effectId: "temperature",
    paramKey: "amount",
    min: -1,
    max: 1,
    step: 0.01
  },
  {
    id: "chroma",
    label: "Chroma",
    effectId: "saturation",
    paramKey: "amount",
    min: -1,
    max: 1,
    step: 0.01
  },
  {
    id: "fade",
    label: "Fade",
    effectId: "fade",
    paramKey: "amount",
    min: 0,
    max: 1,
    step: 0.01
  },
  {
    id: "grain",
    label: "Grain",
    effectId: "grain",
    paramKey: "amount",
    min: 0,
    max: 1,
    step: 0.01
  },
  {
    id: "grain_size",
    label: "Grain size",
    effectId: "grain",
    paramKey: "size",
    min: 0,
    max: 1,
    step: 0.01
  },
  {
    id: "vignette",
    label: "Vignette",
    effectId: "vignette",
    paramKey: "amount",
    min: 0,
    max: 1,
    step: 0.01
  },
  {
    id: "blur",
    label: "Blur",
    effectId: "blur",
    paramKey: "amount",
    min: 0,
    max: 1,
    step: 0.01
  }
];
var DUOTONE_SLIDER = {
  id: "duotone",
  label: "Duotone",
  effectId: "duotone",
  paramKey: "amount",
  min: 0,
  max: 1,
  step: 0.01
};
function clampSliderValue(spec, value) {
  return Math.min(spec.max, Math.max(spec.min, value));
}

// src/packs/regionalSliders.ts
var REGIONAL_SLIDERS = [
  {
    id: "bg_mute",
    label: "Background mute",
    region: "background",
    effectId: "saturation",
    paramKey: "amount",
    min: -1,
    max: 1,
    step: 0.01
  },
  {
    id: "bg_fade",
    label: "Background fade",
    region: "background",
    effectId: "fade",
    paramKey: "amount",
    min: 0,
    max: 1,
    step: 0.01
  },
  {
    id: "bg_blur",
    label: "Background blur",
    region: "background",
    effectId: "blur",
    paramKey: "amount",
    min: 0,
    max: 1,
    step: 0.01
  },
  {
    id: "subject_pop",
    label: "Subject pop",
    region: "subject",
    effectId: "contrast",
    paramKey: "amount",
    min: -1,
    max: 1,
    step: 0.01
  },
  {
    id: "subject_chroma",
    label: "Subject color",
    region: "subject",
    effectId: "saturation",
    paramKey: "amount",
    min: -1,
    max: 1,
    step: 0.01
  }
];
var DEFAULT_DELTA_FRACTION = 0.1;
function defaultDeltaForRegionalSlider(sliderId) {
  const spec = REGIONAL_SLIDERS.find((s) => s.id === sliderId);
  if (!spec) throw new Error(`unknown regional slider ${sliderId}`);
  return DEFAULT_DELTA_FRACTION * (spec.max - spec.min);
}

// src/talk/types.ts
var TALK_PACK_IDS = [
  "warm-film",
  "dusk-grain",
  "flash-raw",
  "cool-chrome",
  "editorial-bw",
  "clean-editorial",
  "muted-split",
  "poster-punch"
];
var TALK_SLIDER_IDS = [
  "exposure",
  "contrast",
  "warmth",
  "chroma",
  "fade",
  "grain",
  "grain_size",
  "vignette",
  "blur",
  "duotone"
];
var TALK_REGIONAL_SLIDER_IDS = [
  "bg_mute",
  "bg_fade",
  "bg_blur",
  "subject_pop",
  "subject_chroma"
];
var TALK_REGIONAL_REGIONS = ["subject", "background"];
var TALK_REGIONAL_PRESET_IDS = [
  "muted_background",
  "subject_pop"
];
var TALK_TEXT_POSITIONS = [
  "top-band",
  "bottom-left",
  "center"
];
var TALK_TYPE_PRESETS = [
  "sans-bold",
  "condensed"
];
var TALK_TRANSFORM_TARGETS = [
  "text",
  "overlay"
];
var DEFAULT_DELTA_FRACTION2 = 0.1;
var DEFAULT_TRANSFORM_NUDGE_XY = 0.08;
var DEFAULT_TRANSFORM_NUDGE_SCALE = 0.1;

// src/canvas/pointerToTransform.ts
var TRANSFORM_XY_MIN = -1.5;
var TRANSFORM_XY_MAX = 1.5;
var TRANSFORM_SCALE_MIN = 0.15;
var TRANSFORM_SCALE_MAX = 4;
function clamp(n, min, max) {
  return Math.min(max, Math.max(min, n));
}
function clampTransform(t) {
  return {
    x: clamp(t.x, TRANSFORM_XY_MIN, TRANSFORM_XY_MAX),
    y: clamp(t.y, TRANSFORM_XY_MIN, TRANSFORM_XY_MAX),
    scaleX: clamp(t.scaleX, TRANSFORM_SCALE_MIN, TRANSFORM_SCALE_MAX),
    scaleY: clamp(t.scaleY, TRANSFORM_SCALE_MIN, TRANSFORM_SCALE_MAX),
    rotation: t.rotation
  };
}

// src/talk/normalize.ts
function sliderSpec(id) {
  if (id === "duotone") return DUOTONE_SLIDER;
  return SEMANTIC_SLIDERS.find((s) => s.id === id) ?? null;
}
function regionalSliderSpec(id) {
  return REGIONAL_SLIDERS.find((s) => s.id === id) ?? null;
}
function isPackId(id) {
  return typeof id === "string" && TALK_PACK_IDS.includes(id);
}
function isSliderId(id) {
  return typeof id === "string" && TALK_SLIDER_IDS.includes(id);
}
function isRegionalSliderId(id) {
  return typeof id === "string" && TALK_REGIONAL_SLIDER_IDS.includes(id);
}
function isRegionalRegion(id) {
  return typeof id === "string" && TALK_REGIONAL_REGIONS.includes(id);
}
function isRegionalPresetId(id) {
  return typeof id === "string" && TALK_REGIONAL_PRESET_IDS.includes(id);
}
function requireMask(ctx, tool) {
  if (!ctx.hasMask) {
    return {
      ok: false,
      code: "NO_MASK",
      message: `${tool} requires an active person mask on main`
    };
  }
  return null;
}
function defaultDelta(spec) {
  return DEFAULT_DELTA_FRACTION2 * (spec.max - spec.min);
}
function currentSliderAmount(ctx, sliderId) {
  const s = ctx.sliders;
  switch (sliderId) {
    case "exposure":
      return s.exposure;
    case "contrast":
      return s.contrast;
    case "warmth":
      return s.warmth;
    case "chroma":
      return s.chroma;
    case "fade":
      return s.fade;
    case "grain":
      return s.grain;
    case "grain_size":
      return s.grain_size ?? 0.5;
    case "vignette":
      return s.vignette;
    case "blur":
      return s.blur ?? 0;
    case "duotone":
      return s.duotone ?? 0;
    default:
      return 0;
  }
}
function currentRegionalSliderAmount(ctx, sliderId) {
  return ctx.regionalSliders?.[sliderId] ?? 0;
}
function parseRefuse(raw) {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    return { ok: false, code: "SCHEMA", message: "refuse must be an object" };
  }
  const rec = raw;
  if (typeof rec.code !== "string" || !rec.code) {
    return { ok: false, code: "SCHEMA", message: "refuse.code required" };
  }
  if (typeof rec.reason !== "string" || !rec.reason) {
    return { ok: false, code: "SCHEMA", message: "refuse.reason required" };
  }
  return { code: rec.code, reason: rec.reason };
}
function parseApplyPack(raw) {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    return { ok: false, code: "SCHEMA", message: "applyPack must be an object" };
  }
  const rec = raw;
  if (!isPackId(rec.packId)) {
    return {
      ok: false,
      code: "UNKNOWN_PACK",
      message: `unknown packId "${String(rec.packId)}"`
    };
  }
  let intensity;
  if (rec.intensity !== void 0) {
    if (typeof rec.intensity !== "number" || !Number.isFinite(rec.intensity)) {
      return { ok: false, code: "SCHEMA", message: "applyPack.intensity must be a number" };
    }
    intensity = Math.min(1, Math.max(0, rec.intensity));
  }
  return { packId: rec.packId, ...intensity !== void 0 ? { intensity } : {} };
}
function parseApplyRegionalPreset(raw, ctx) {
  const maskErr = requireMask(ctx, "applyRegionalPreset");
  if (maskErr) return maskErr;
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    return { ok: false, code: "SCHEMA", message: "applyRegionalPreset must be an object" };
  }
  const rec = raw;
  if (!isRegionalPresetId(rec.presetId)) {
    return {
      ok: false,
      code: "SCHEMA",
      message: `unknown regional presetId "${String(rec.presetId)}"`
    };
  }
  return { presetId: rec.presetId };
}
function parseSetTextHint(raw) {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    return { ok: false, code: "SCHEMA", message: "setTextHint must be an object" };
  }
  const rec = raw;
  const out = {};
  if (rec.position !== void 0) {
    if (typeof rec.position !== "string" || !TALK_TEXT_POSITIONS.includes(rec.position)) {
      return { ok: false, code: "SCHEMA", message: `invalid text position "${String(rec.position)}"` };
    }
    out.position = rec.position;
  }
  if (rec.typePreset !== void 0) {
    if (typeof rec.typePreset !== "string" || !TALK_TYPE_PRESETS.includes(rec.typePreset)) {
      return {
        ok: false,
        code: "SCHEMA",
        message: `invalid typePreset "${String(rec.typePreset)}"`
      };
    }
    out.typePreset = rec.typePreset;
  }
  if (!out.position && !out.typePreset) {
    return {
      ok: false,
      code: "SCHEMA",
      message: "setTextHint requires position and/or typePreset"
    };
  }
  return out;
}
function isTransformTarget(id) {
  return typeof id === "string" && TALK_TRANSFORM_TARGETS.includes(id);
}
function parseSetTextContent(raw) {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    return { ok: false, code: "SCHEMA", message: "setTextContent must be an object" };
  }
  const rec = raw;
  if (typeof rec.content !== "string") {
    return { ok: false, code: "SCHEMA", message: "setTextContent.content must be a string" };
  }
  const content = rec.content.slice(0, 200);
  return { content };
}
function currentTargetTransform(ctx, target) {
  if (target === "text") {
    return ctx.textTransform ?? { x: 0, y: -0.35, scaleX: 1, scaleY: 1 };
  }
  return ctx.overlayTransform ?? { x: 0, y: 0, scaleX: 1, scaleY: 1 };
}
function parseSetTransform(raw) {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    return { ok: false, code: "SCHEMA", message: "setTransform must be an object" };
  }
  const rec = raw;
  if (!isTransformTarget(rec.target)) {
    return {
      ok: false,
      code: "SCHEMA",
      message: `setTransform.target must be text or overlay`
    };
  }
  const out = { target: rec.target };
  for (const key of ["x", "y", "scaleX", "scaleY"]) {
    if (rec[key] === void 0) continue;
    if (typeof rec[key] !== "number" || !Number.isFinite(rec[key])) {
      return { ok: false, code: "SCHEMA", message: `setTransform.${key} must be a finite number` };
    }
    out[key] = rec[key];
  }
  if (out.x === void 0 && out.y === void 0 && out.scaleX === void 0 && out.scaleY === void 0) {
    return {
      ok: false,
      code: "SCHEMA",
      message: "setTransform requires at least one of x,y,scaleX,scaleY"
    };
  }
  const clamped = clampTransform({
    x: out.x ?? 0,
    y: out.y ?? 0,
    scaleX: out.scaleX ?? 1,
    scaleY: out.scaleY ?? out.scaleX ?? 1,
    rotation: 0
  });
  if (out.x !== void 0) out.x = clamped.x;
  if (out.y !== void 0) out.y = clamped.y;
  if (out.scaleX !== void 0) out.scaleX = clamped.scaleX;
  if (out.scaleY !== void 0) out.scaleY = clamped.scaleY;
  return out;
}
function parseNudgeTransform(raw, ctx) {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    return { ok: false, code: "SCHEMA", message: "nudgeTransform must be an object" };
  }
  const rec = raw;
  if (!isTransformTarget(rec.target)) {
    return {
      ok: false,
      code: "SCHEMA",
      message: "nudgeTransform.target must be text or overlay"
    };
  }
  const readDelta = (key, defaultMag) => {
    if (!(key in rec) || rec[key] === void 0) {
      return { ok: true, value: void 0 };
    }
    if (rec[key] === null) {
      return { ok: true, value: defaultMag };
    }
    if (typeof rec[key] !== "number" || !Number.isFinite(rec[key])) {
      return {
        ok: false,
        code: "SCHEMA",
        message: `nudgeTransform.${key} must be a finite number`
      };
    }
    return { ok: true, value: rec[key] };
  };
  const dxR = readDelta("dx", DEFAULT_TRANSFORM_NUDGE_XY);
  if ("code" in dxR) return dxR;
  const dyR = readDelta("dy", DEFAULT_TRANSFORM_NUDGE_XY);
  if ("code" in dyR) return dyR;
  const dsR = readDelta("dScale", DEFAULT_TRANSFORM_NUDGE_SCALE);
  if ("code" in dsR) return dsR;
  if (dxR.value === void 0 && dyR.value === void 0 && dsR.value === void 0) {
    return {
      ok: false,
      code: "SCHEMA",
      message: "nudgeTransform requires dx, dy, and/or dScale"
    };
  }
  const cur = currentTargetTransform(ctx, rec.target);
  const dx = dxR.value ?? 0;
  const dy = dyR.value ?? 0;
  const dScale = dsR.value ?? 0;
  const next = clampTransform({
    x: cur.x + dx,
    y: cur.y + dy,
    scaleX: cur.scaleX + dScale,
    scaleY: cur.scaleY + dScale,
    rotation: 0
  });
  const out = { target: rec.target };
  if (dxR.value !== void 0) out.x = next.x;
  if (dyR.value !== void 0) out.y = next.y;
  if (dsR.value !== void 0) {
    out.scaleX = next.scaleX;
    out.scaleY = next.scaleY;
  }
  return out;
}
function mergeSetTransform(base, next) {
  if (!base || base.target !== next.target) return next;
  return {
    target: next.target,
    x: next.x ?? base.x,
    y: next.y ?? base.y,
    scaleX: next.scaleX ?? base.scaleX,
    scaleY: next.scaleY ?? base.scaleY
  };
}
function parseGlobalPatch(raw, ctx, index) {
  const op = raw.op;
  if (op !== "set_slider" && op !== "delta_slider") {
    return {
      ok: false,
      code: "SCHEMA",
      message: `patches[${index}].op must be set_slider or delta_slider`
    };
  }
  if (!isSliderId(raw.sliderId)) {
    return {
      ok: false,
      code: "UNKNOWN_SLIDER",
      message: `unknown sliderId "${String(raw.sliderId)}"`
    };
  }
  const spec = sliderSpec(raw.sliderId);
  if (!spec) {
    return {
      ok: false,
      code: "UNKNOWN_SLIDER",
      message: `unknown sliderId "${raw.sliderId}"`
    };
  }
  if (op === "set_slider") {
    if (typeof raw.value !== "number" || !Number.isFinite(raw.value)) {
      return {
        ok: false,
        code: "SCHEMA",
        message: `patches[${index}].value must be a finite number`
      };
    }
    const value = clampSliderValue(spec, raw.value);
    return { op: "set_slider", sliderId: raw.sliderId, value };
  }
  let delta;
  if (raw.delta === void 0 || raw.delta === null) {
    delta = defaultDelta(spec);
  } else if (typeof raw.delta !== "number" || !Number.isFinite(raw.delta)) {
    return {
      ok: false,
      code: "SCHEMA",
      message: `patches[${index}].delta must be a finite number`
    };
  } else {
    delta = raw.delta;
  }
  const next = clampSliderValue(
    spec,
    currentSliderAmount(ctx, raw.sliderId) + delta
  );
  return { op: "set_slider", sliderId: raw.sliderId, value: next };
}
function parseRegionalPatch(raw, ctx, index) {
  const maskErr = requireMask(ctx, "regional slider patch");
  if (maskErr) return maskErr;
  const op = raw.op;
  if (op !== "set_regional_slider" && op !== "delta_regional_slider") {
    return {
      ok: false,
      code: "SCHEMA",
      message: `patches[${index}].op must be set_regional_slider or delta_regional_slider`
    };
  }
  if (!isRegionalRegion(raw.region)) {
    return {
      ok: false,
      code: "SCHEMA",
      message: `patches[${index}].region must be subject or background`
    };
  }
  if (!isRegionalSliderId(raw.sliderId)) {
    return {
      ok: false,
      code: "UNKNOWN_SLIDER",
      message: `unknown regional sliderId "${String(raw.sliderId)}"`
    };
  }
  const spec = regionalSliderSpec(raw.sliderId);
  if (!spec) {
    return {
      ok: false,
      code: "UNKNOWN_SLIDER",
      message: `unknown regional sliderId "${raw.sliderId}"`
    };
  }
  if (spec.region !== raw.region) {
    return {
      ok: false,
      code: "SCHEMA",
      message: `patches[${index}]: slider "${raw.sliderId}" belongs to region "${spec.region}"`
    };
  }
  const clampRegional = (v) => Math.min(spec.max, Math.max(spec.min, v));
  if (op === "set_regional_slider") {
    if (typeof raw.value !== "number" || !Number.isFinite(raw.value)) {
      return {
        ok: false,
        code: "SCHEMA",
        message: `patches[${index}].value must be a finite number`
      };
    }
    return {
      op: "set_regional_slider",
      region: raw.region,
      sliderId: raw.sliderId,
      value: clampRegional(raw.value)
    };
  }
  let delta;
  if (raw.delta === void 0 || raw.delta === null) {
    delta = defaultDeltaForRegionalSlider(raw.sliderId);
  } else if (typeof raw.delta !== "number" || !Number.isFinite(raw.delta)) {
    return {
      ok: false,
      code: "SCHEMA",
      message: `patches[${index}].delta must be a finite number`
    };
  } else {
    delta = raw.delta;
  }
  const next = clampRegional(
    currentRegionalSliderAmount(ctx, raw.sliderId) + delta
  );
  return {
    op: "set_regional_slider",
    region: raw.region,
    sliderId: raw.sliderId,
    value: next
  };
}
function parsePatch(raw, ctx, index) {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    return { ok: false, code: "SCHEMA", message: `patches[${index}] must be an object` };
  }
  const rec = raw;
  const op = rec.op;
  if (op === "set_slider" || op === "delta_slider") {
    return parseGlobalPatch(rec, ctx, index);
  }
  if (op === "set_regional_slider" || op === "delta_regional_slider") {
    return parseRegionalPatch(rec, ctx, index);
  }
  return {
    ok: false,
    code: "SCHEMA",
    message: `patches[${index}].op unknown`
  };
}
function updateCtxAfterPatch(ctx, patch) {
  if (patch.op === "set_slider") {
    return {
      ...ctx,
      sliders: { ...ctx.sliders, [patch.sliderId]: patch.value }
    };
  }
  if (patch.op === "set_regional_slider") {
    return {
      ...ctx,
      regionalSliders: {
        bg_mute: ctx.regionalSliders?.bg_mute ?? 0,
        bg_fade: ctx.regionalSliders?.bg_fade ?? 0,
        bg_blur: ctx.regionalSliders?.bg_blur ?? 0,
        subject_pop: ctx.regionalSliders?.subject_pop ?? 0,
        subject_chroma: ctx.regionalSliders?.subject_chroma ?? 0,
        [patch.sliderId]: patch.value
      }
    };
  }
  return ctx;
}
function normalizeTalkResponse(raw, recipeContext) {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    return { ok: false, code: "SCHEMA", message: "TalkResponse must be an object" };
  }
  const rec = raw;
  const out = {};
  let ctx = {
    packId: recipeContext.packId,
    packVersion: recipeContext.packVersion,
    sliders: { ...recipeContext.sliders },
    mainEffectIds: recipeContext.mainEffectIds ? [...recipeContext.mainEffectIds] : void 0,
    hasMask: recipeContext.hasMask,
    regionalSliders: recipeContext.regionalSliders ? { ...recipeContext.regionalSliders } : void 0,
    hasOverlay: recipeContext.hasOverlay,
    hasText: recipeContext.hasText,
    textContent: recipeContext.textContent,
    textTransform: recipeContext.textTransform ? { ...recipeContext.textTransform } : void 0,
    overlayTransform: recipeContext.overlayTransform ? { ...recipeContext.overlayTransform } : void 0,
    selection: recipeContext.selection
  };
  if ("refuse" in rec && rec.refuse !== void 0 && rec.refuse !== null) {
    const refuse = parseRefuse(rec.refuse);
    if ("ok" in refuse && refuse.ok === false) return refuse;
    out.refuse = refuse;
    if (typeof rec.say === "string" && rec.say.trim()) {
      out.say = rec.say.trim().slice(0, 200);
    }
    return { ok: true, response: out };
  }
  if ("applyPack" in rec && rec.applyPack !== void 0 && rec.applyPack !== null) {
    const pack = parseApplyPack(rec.applyPack);
    if ("ok" in pack && pack.ok === false) return pack;
    out.applyPack = pack;
  }
  if ("applyRegionalPreset" in rec && rec.applyRegionalPreset !== void 0 && rec.applyRegionalPreset !== null) {
    const preset = parseApplyRegionalPreset(rec.applyRegionalPreset, ctx);
    if ("ok" in preset && preset.ok === false) return preset;
    out.applyRegionalPreset = preset;
  }
  if ("setTextHint" in rec && rec.setTextHint !== void 0 && rec.setTextHint !== null) {
    const hint = parseSetTextHint(rec.setTextHint);
    if ("ok" in hint && hint.ok === false) return hint;
    out.setTextHint = hint;
  }
  if ("setTextContent" in rec && rec.setTextContent !== void 0 && rec.setTextContent !== null) {
    const content = parseSetTextContent(rec.setTextContent);
    if ("ok" in content && content.ok === false) return content;
    out.setTextContent = content;
  }
  if ("setTransform" in rec && rec.setTransform !== void 0 && rec.setTransform !== null) {
    const tf = parseSetTransform(rec.setTransform);
    if ("ok" in tf && tf.ok === false) return tf;
    out.setTransform = tf;
  }
  if ("nudgeTransform" in rec && rec.nudgeTransform !== void 0 && rec.nudgeTransform !== null) {
    const nudged = parseNudgeTransform(rec.nudgeTransform, ctx);
    if ("ok" in nudged && nudged.ok === false) return nudged;
    out.setTransform = mergeSetTransform(out.setTransform, nudged);
  }
  if ("regenerateMask" in rec && rec.regenerateMask !== void 0 && rec.regenerateMask !== null) {
    if (typeof rec.regenerateMask !== "boolean") {
      return { ok: false, code: "SCHEMA", message: "regenerateMask must be boolean" };
    }
    const maskErr = requireMask(ctx, "regenerateMask");
    if (maskErr) return maskErr;
    if (rec.regenerateMask) {
      out.regenerateMask = true;
    }
  }
  if ("patches" in rec && rec.patches !== void 0 && rec.patches !== null) {
    if (!Array.isArray(rec.patches)) {
      return { ok: false, code: "SCHEMA", message: "patches must be an array" };
    }
    const patches = [];
    for (let i = 0; i < rec.patches.length; i++) {
      const patch = parsePatch(rec.patches[i], ctx, i);
      if ("ok" in patch && patch.ok === false) return patch;
      patches.push(patch);
      ctx = updateCtxAfterPatch(ctx, patch);
    }
    if (patches.length > 0) out.patches = patches;
  }
  if (typeof rec.say === "string" && rec.say.trim()) {
    out.say = rec.say.trim().slice(0, 200);
  }
  if (!out.applyPack && !out.patches?.length && !out.applyRegionalPreset && !out.setTextHint && !out.setTextContent && !out.setTransform && !out.regenerateMask && !out.refuse) {
    return {
      ok: false,
      code: "SCHEMA",
      message: "TalkResponse empty: need applyPack, patches, applyRegionalPreset, setTextHint, setTextContent, setTransform/nudgeTransform, regenerateMask, or refuse"
    };
  }
  return { ok: true, response: out };
}

// api/_lib/env.ts
function getGeminiApiKey() {
  const key = process.env.GEMINI_API_KEY?.trim();
  return key ? key : null;
}
var GEMINI_MODEL_ID = "gemini-2.5-flash";
var RATE_LIMIT_WINDOW_MS = 6e4;
var RATE_LIMIT_MAX = 20;

// api/_lib/gemini.ts
import { GoogleGenAI } from "@google/genai";

// src/talk/schema.ts
var TALK_RESPONSE_SCHEMA = {
  type: "OBJECT",
  properties: {
    applyPack: {
      type: "OBJECT",
      properties: {
        packId: {
          type: "STRING",
          enum: [...TALK_PACK_IDS],
          description: "Catalog pack id only"
        },
        intensity: {
          type: "NUMBER",
          description: "Optional pack intensity 0..1; default 1"
        }
      },
      required: ["packId"]
    },
    patches: {
      type: "ARRAY",
      items: {
        type: "OBJECT",
        properties: {
          op: {
            type: "STRING",
            enum: [
              "set_slider",
              "delta_slider",
              "set_regional_slider",
              "delta_regional_slider"
            ]
          },
          sliderId: {
            type: "STRING",
            enum: [...TALK_SLIDER_IDS, ...TALK_REGIONAL_SLIDER_IDS],
            description: "Global semantic slider or regional slider id"
          },
          region: {
            type: "STRING",
            enum: [...TALK_REGIONAL_REGIONS],
            description: "Required for regional slider ops"
          },
          value: {
            type: "NUMBER",
            description: "Absolute value for set_slider / set_regional_slider"
          },
          delta: {
            type: "NUMBER",
            description: "Relative delta for delta_slider / delta_regional_slider; omit size only if unsure \u2014 host fills ~0.1 span"
          }
        },
        required: ["op"]
      }
    },
    applyRegionalPreset: {
      type: "OBJECT",
      properties: {
        presetId: {
          type: "STRING",
          enum: [...TALK_REGIONAL_PRESET_IDS],
          description: "Closed regional template; requires hasMask in context"
        }
      },
      required: ["presetId"]
    },
    setTextHint: {
      type: "OBJECT",
      properties: {
        position: {
          type: "STRING",
          enum: [...TALK_TEXT_POSITIONS]
        },
        typePreset: {
          type: "STRING",
          enum: [...TALK_TYPE_PRESETS]
        }
      },
      description: "Optional text layout hint (3 positions, 2 presets)"
    },
    setTextContent: {
      type: "OBJECT",
      properties: {
        content: {
          type: "STRING",
          description: "Exact title/caption string to set on the single text object"
        }
      },
      required: ["content"],
      description: "Set or create the single text object's content (not copywriting Autofill)"
    },
    nudgeTransform: {
      type: "OBJECT",
      properties: {
        target: {
          type: "STRING",
          enum: [...TALK_TRANSFORM_TARGETS]
        },
        dx: {
          type: "NUMBER",
          description: "NDC x delta; omit for default ~0.08 when intent implies horizontal move"
        },
        dy: {
          type: "NUMBER",
          description: "NDC y delta (+up); omit for default ~0.08 when intent implies vertical move"
        },
        dScale: {
          type: "NUMBER",
          description: "Uniform scale delta; omit for default ~0.1 when intent implies bigger/smaller"
        }
      },
      required: ["target"],
      description: "Relative move/scale for text or overlay (prefer for 'up a bit')"
    },
    setTransform: {
      type: "OBJECT",
      properties: {
        target: {
          type: "STRING",
          enum: [...TALK_TRANSFORM_TARGETS]
        },
        x: { type: "NUMBER" },
        y: { type: "NUMBER" },
        scaleX: { type: "NUMBER" },
        scaleY: { type: "NUMBER" }
      },
      required: ["target"],
      description: "Absolute transform fields for text or overlay (e.g. center)"
    },
    regenerateMask: {
      type: "BOOLEAN",
      description: "When true, host re-runs client mask worker (local only; no image bytes sent)"
    },
    say: {
      type: "STRING",
      description: "Optional \u22641 short line for UI toast; never recipe truth"
    },
    refuse: {
      type: "OBJECT",
      properties: {
        code: { type: "STRING" },
        reason: { type: "STRING" }
      },
      required: ["code", "reason"],
      description: "Use for generative/inpaint/beach/remove-person or out-of-scope intents"
    }
  }
};
var TALK_SYSTEM_PROMPT = `You are Prism's parametric talk router \u2014 NOT a generative image editor.

Map the user's short mood/refinement sentence to structured JSON only:
- applyPack: one of warm-film | dusk-grain | flash-raw | cool-chrome | editorial-bw | clean-editorial | muted-split | poster-punch (optional intensity 0..1)
- patches: set_slider (absolute) or delta_slider (relative). Prefer delta_slider for "less/more/warmer/cooler".
- Slider ids: exposure, contrast, warmth, chroma, fade, grain, grain_size, vignette, blur, duotone
- When recipeContext.hasMask is true, prefer regional tools for subject/background language:
  - set_regional_slider / delta_regional_slider with region subject|background and sliderId bg_mute | bg_fade | bg_blur | subject_pop | subject_chroma
  - applyRegionalPreset: muted_background (desaturated faded bg) or subject_pop (more contrast/color on subject)
  - regenerateMask: true when user asks to redo/fix the person mask (client worker only)
- setTextHint: optional { position: top-band|bottom-left|center, typePreset: sans-bold|condensed } for poster type snaps
- setTextContent: { content } to set/create the single title string (e.g. "set title to Prism")
- nudgeTransform: { target: text|overlay, dx?, dy?, dScale? } for "move title up / left / bigger" \u2014 NDC +y is up; prefer over inventing free pointers
- setTransform: { target, x?, y?, scaleX?, scaleY? } for absolute placement (e.g. center)
- Use recipeContext.selection, textTransform, overlayTransform, hasText, hasOverlay for spatial language
- say: optional one short line for UI; never the look truth
- refuse: for generative/inpaint/outpaint/"put me on a beach"/remove person/beauty retouch/open-world invent/extra layers

Rules:
1. You NEVER invent free shader paths, new effect ids, PathPatch strings, or mood JSON that bypasses packs/sliders.
2. Refinement needs recipeContext sliders \u2014 apply relative deltas with correct sign ("less grain" \u2192 negative grain delta).
3. When hasMask, "mute the background" \u2192 delta_regional_slider bg_mute negative OR applyRegionalPreset muted_background; "make me pop" \u2192 subject_pop positive OR preset subject_pop; soft bg \u2192 bg_blur.
4. Regional tools require hasMask; if absent, use global sliders only.
5. Prefer MULTI-TOOL turns when the user stacks intents (e.g. warm film + mute bg + title bottom + move title up). You MAY combine applyPack, patches, applyRegionalPreset, setTextHint, setTextContent, nudgeTransform/setTransform, and regenerateMask in one turn (regenerateMask at most once).
6. Text content edits ONLY via setTextContent. Spatial moves ONLY via nudgeTransform/setTransform or setTextHint snaps \u2014 never invent overlay pixels or a second text object.
7. If intent is generative, beach, invent layers, or outside closed controls \u2192 set refuse (no writes).
8. Text-only router; ignore any request to analyze or upload image bytes.`;

// api/_lib/gemini.ts
async function generateTalkJson(apiKey, request, options = {}) {
  const ai = new GoogleGenAI({ apiKey });
  const model = options.model ?? GEMINI_MODEL_ID;
  const userPayload = [
    "User request and current recipe context (JSON):",
    JSON.stringify(
      {
        text: request.text,
        recipeContext: request.recipeContext
      },
      null,
      2
    )
  ].join("\n");
  try {
    const response = await ai.models.generateContent({
      model,
      contents: userPayload,
      config: {
        systemInstruction: TALK_SYSTEM_PROMPT,
        responseMimeType: "application/json",
        responseSchema: TALK_RESPONSE_SCHEMA,
        abortSignal: options.signal
      }
    });
    const text = response.text;
    if (!text || !text.trim()) {
      return { ok: false, code: "SCHEMA", message: "empty model response" };
    }
    let raw;
    try {
      raw = JSON.parse(text);
    } catch {
      return { ok: false, code: "SCHEMA", message: "model response was not JSON" };
    }
    return { ok: true, raw };
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    const lower = msg.toLowerCase();
    if (lower.includes("abort") || lower.includes("timeout") || lower.includes("timed out")) {
      return { ok: false, code: "TIMEOUT", message: msg };
    }
    if (lower.includes("429") || lower.includes("resource_exhausted")) {
      return { ok: false, code: "HTTP_429", message: msg };
    }
    if (lower.includes("401") || lower.includes("403") || lower.includes("api key")) {
      return { ok: false, code: "HTTP_401", message: msg };
    }
    return { ok: false, code: "HTTP_502", message: msg };
  }
}

// api/_lib/talkCore.ts
var rateByIp = /* @__PURE__ */ new Map();
var SERVER_TIMEOUT_MS = 14e3;
function clientIpFromForwarded(forwarded, fallback) {
  if (typeof forwarded === "string" && forwarded.length > 0) {
    return forwarded.split(",")[0].trim();
  }
  if (Array.isArray(forwarded) && forwarded[0]) {
    return forwarded[0].split(",")[0].trim();
  }
  return fallback;
}
function allowRate(ip) {
  const now = Date.now();
  const prev = rateByIp.get(ip) ?? [];
  const recent = prev.filter((t) => now - t < RATE_LIMIT_WINDOW_MS);
  if (recent.length >= RATE_LIMIT_MAX) {
    rateByIp.set(ip, recent);
    return false;
  }
  recent.push(now);
  rateByIp.set(ip, recent);
  return true;
}
function isRecipeContext(v) {
  if (v === null || typeof v !== "object" || Array.isArray(v)) return false;
  const rec = v;
  if (!("sliders" in rec) || rec.sliders === null || typeof rec.sliders !== "object") {
    return false;
  }
  const s = rec.sliders;
  const required = [
    "exposure",
    "contrast",
    "warmth",
    "chroma",
    "fade",
    "grain",
    "vignette"
  ];
  for (const k of required) {
    if (typeof s[k] !== "number" || !Number.isFinite(s[k])) return false;
  }
  return true;
}
function parseTalkRequest(raw) {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    return "body must be an object";
  }
  const rec = raw;
  if (typeof rec.text !== "string" || !rec.text.trim()) {
    return "text must be a non-empty string";
  }
  if (!isRecipeContext(rec.recipeContext)) {
    return "recipeContext.sliders with finite amounts required";
  }
  if ("image" in rec || "imageBase64" in rec || "blob" in rec || "pixels" in rec) {
    return "image bytes not allowed in talk request";
  }
  return {
    text: rec.text.trim().slice(0, 2e3),
    recipeContext: rec.recipeContext
  };
}
function parseRawBody(rawBody) {
  if (typeof rawBody === "string") {
    try {
      return { ok: true, parsed: JSON.parse(rawBody || "{}") };
    } catch {
      return {
        ok: false,
        result: { ok: false, status: 400, code: "SCHEMA", message: "request body was not JSON" }
      };
    }
  }
  return { ok: true, parsed: rawBody };
}
async function processTalk(rawBody, options) {
  if (!allowRate(options.ip)) {
    return {
      ok: false,
      status: 429,
      code: "RATE_LIMIT",
      message: "too many talk requests; try again shortly"
    };
  }
  const apiKey = getGeminiApiKey();
  if (!apiKey) {
    return {
      ok: false,
      status: 503,
      code: "MISSING_KEY",
      message: "GEMINI_API_KEY not set on server \u2014 Lab packs/sliders still work"
    };
  }
  const bodyOrErr = parseRawBody(rawBody);
  if (!bodyOrErr.ok) {
    return bodyOrErr.result;
  }
  const parsed = bodyOrErr.parsed;
  const requestOrErr = parseTalkRequest(parsed);
  if (typeof requestOrErr === "string") {
    return { ok: false, status: 400, code: "HTTP_400", message: requestOrErr };
  }
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), SERVER_TIMEOUT_MS);
  try {
    const gemini = await generateTalkJson(apiKey, requestOrErr, {
      signal: controller.signal
    });
    if (!gemini.ok) {
      const status = gemini.code === "TIMEOUT" ? 504 : gemini.code === "HTTP_429" ? 429 : gemini.code === "HTTP_401" ? 401 : 502;
      return { ok: false, status, code: gemini.code, message: gemini.message };
    }
    const normalized = normalizeTalkResponse(gemini.raw, requestOrErr.recipeContext);
    if (!normalized.ok) {
      return { ok: false, status: 422, code: normalized.code, message: normalized.message };
    }
    return { ok: true, status: 200, response: normalized.response };
  } finally {
    clearTimeout(timer);
  }
}

// api/talk.entry.ts
function sendJson(res, status, body) {
  const payload = JSON.stringify(body);
  res.statusCode = status;
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  res.setHeader("Cache-Control", "no-store");
  res.end(payload);
}
function sendError(res, status, code, message) {
  sendJson(res, status, { error: { code, message } });
}
async function readRawBody(req) {
  if (req.body !== void 0) {
    return req.body;
  }
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (c) => {
      chunks.push(c);
      if (chunks.reduce((n, b) => n + b.length, 0) > 64e3) {
        reject(new Error("body too large"));
        req.destroy();
      }
    });
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}
async function handler(req, res) {
  if (req.method === "OPTIONS") {
    res.statusCode = 204;
    res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type");
    res.end();
    return;
  }
  if (req.method !== "POST") {
    sendError(res, 405, "HTTP_400", "POST only");
    return;
  }
  const ip = clientIpFromForwarded(
    req.headers["x-forwarded-for"],
    req.socket?.remoteAddress ?? "unknown"
  );
  let rawBody;
  try {
    rawBody = await readRawBody(req);
  } catch (e) {
    sendError(
      res,
      400,
      "HTTP_400",
      e instanceof Error ? e.message : "failed to read body"
    );
    return;
  }
  try {
    const result = await processTalk(rawBody, { ip });
    if (!result.ok) {
      sendError(res, result.status, result.code, result.message);
      return;
    }
    sendJson(res, 200, result.response);
  } catch (e) {
    sendError(
      res,
      500,
      "HTTP_500",
      e instanceof Error ? e.message : "talk handler failed"
    );
  }
}
export {
  handler as default
};
